version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    labels: ["type:enhancement", "area:automation"]
    open-pull-requests-limit: 5
  - package-ecosystem: nuget
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
    labels: ["type:enhancement", "area:dependencies"]
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /Tools/Automation
    target-branch: develop
    schedule:
      interval: weekly
    labels: ["type:enhancement", "area:automation"]
    open-pull-requests-limit: 5
